# Generated by Django 4.2.7 on 2024-02-23 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('numero_casa', models.IntegerField(verbose_name='Número')),
                ('barrio', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Poniente', 'Poniente'), ('Oriente', 'Oriente')], max_length=50, verbose_name='Barrio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('Gasto', 'Gasto'), ('Productos comprado y/o elaborados para la venta', 'Productos comprado y/o elaborados para la venta')], max_length=60, verbose_name='Selecciona un tipo')),
                ('forma_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Trasferencia Bancaria', 'Trasferencia Bancaria'), ('Tarjeta Crédito/Débito', 'Tarjeta Crédito/Débito')], max_length=60, verbose_name='Forma de pago')),
                ('monto', models.PositiveIntegerField(verbose_name='Costo Total')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('descuento_2da_unidad', models.PositiveIntegerField(verbose_name='Descuento en Segunda Unidad')),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Torta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('precio_15p', models.PositiveIntegerField(default=0, verbose_name='Precio_15p')),
                ('precio_24p', models.PositiveIntegerField(default=0, verbose_name='Precio_24p')),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forma_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Trasferencia Bancaria', 'Trasferencia Bancaria'), ('Tarjeta Crédito/Débito', 'Tarjeta Crédito/Débito')], max_length=60, verbose_name='Forma de pago')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('monto_total', models.IntegerField(verbose_name='Monto Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.venta'),
        ),
    ]
