# Generated by Django 4.2.7 on 2024-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_cliente_detalleventa_gasto_proveedor_snack_torta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='tipo',
            field=models.CharField(choices=[('Torta', 'Torta'), ('Snack', 'Snack')], default='', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='torta',
            name='tipo',
            field=models.CharField(choices=[('Torta', 'Torta'), ('Snack', 'Snack')], default='', max_length=10, verbose_name='Tipo'),
        ),
    ]
