# Generated by Django 4.2.7 on 2024-02-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_snack_tipo_torta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='descuento_2da_unidad',
            field=models.IntegerField(default=0, verbose_name='Descuento en Segunda Unidad'),
        ),
    ]
