# Generated by Django 4.2.7 on 2024-02-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_snack_descuento_2da_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='tamaño',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
